import type { ParamDocText } from "./types";

/**
 * English text for the parameter reference — one file per language, exactly
 * like `messages/<locale>/<ns>.json`.
 *
 * French (`./params`) is the source: it decides WHICH parameters exist, their
 * type, their default and their allowed values. This file only carries the
 * words. `tests/unit-docs-locale.test.ts` fails when a documented path has no
 * entry here, or when an entry drops the French "effect"/"pitfalls" — a
 * warning that disappears in translation is information lost, not a
 * translation.
 *
 * Not here, deliberately: anything the SMS assistant itself reads. Its prompt
 * is written in the language of its own configuration, never in the language
 * of the administrator's screen.
 */
export const PARAM_DOCS_EN: Record<string, ParamDocText> = {
  "identity.mode": {
    label: "Identity mode",
    what: "Determines on whose behalf the assistant writes: the team, or a named person in your organization.",
    why: "Writing on behalf of a person creates an expectation: whoever answers should be that person. \"Team\" avoids that implicit promise when follow-up is spread across several people.",
    effect: "Compiled into layer L1. In \"named person\" mode, the name appears in the introduction and the appointment is announced as being with that person.",
    pitfalls: "Naming a broker who will not do the follow-up: the client asks for that person on the phone and you have to walk it back. Symptom: clients saying \"I was told I would be speaking with…\".",
    allowed: {
      "team": "Team — \"the Groupe Nexus team\"",
      "named_person": "Named person — one specific broker",
    },
  },
  "identity.orgName": {
    label: "Organization name",
    what: "The company name the assistant uses to introduce itself.",
    why: "CASL requires every commercial message to clearly identify the sender. This string is what fulfils that obligation.",
    effect: "Injected in L1 and available as {{org}} in the turn template. The \"identify_sender\" rule checks that the first message contains it.",
    pitfalls: "A name different from the one the client saw on the Facebook ad: they do not make the connection and report the message as spam. Symptom: a high opt-out rate right from the first send.",
  },
  "identity.brokerName": {
    label: "Broker name",
    what: "The broker the meeting is booked with.",
    why: "The client agrees to an appointment with someone, not with a company. Naming the person makes the offer concrete.",
    effect: "Injected in L1 and into the calendar event title.",
    pitfalls: "A spelling that differs from the OACIQ licence or the website sows doubt.",
  },
  "identity.brokerUserId": {
    label: "Broker account",
    what: "The CRM user matching the named broker. Required in \"named person\" mode.",
    why: "Tying the assistant to a real account lets you assign appointments and conversations to the right person — and makes it impossible to invent a name that does not exist in the team.",
    effect: "Used as the owner of the appointment created. When an assistant is imported, this field has to be re-bound to a local user.",
    pitfalls: "Left empty in \"named person\" mode: compilation still passes, but appointments fall back to the first active admin.",
  },
  "identity.signature": {
    label: "Signature",
    what: "Whether or not a signature is added at the end of messages.",
    why: "In SMS, a signature eats characters and pushes the question further away. It humanizes, but every send repeats it.",
    effect: "Compiled in L1 as a writing instruction.",
    pitfalls: "Signing every message in a conversation gives it a template tone; the value is mostly on first contact.",
    allowed: {
      "none": "None — the message ends on the question",
      "first_name": "First name — \"— Alex\"",
      "full_name": "Full name — \"— Alex-Honoré\"",
      "org": "Organization — \"— Groupe Nexus\"",
      "custom": "Custom — the text you write",
    },
  },
  "identity.signatureText": {
    label: "Signature text",
    what: "The exact signature, used when the signature mode is \"Custom\".",
    why: "The derived forms (first name, full name, organization) do not cover everything: \"— The Nexus team\" or \"— Alex, real-estate broker\" fit none of them.",
    effect: "Appended as-is at the end of messages, with no further processing.",
    pitfalls: "A long signature is repeated on EVERY message and counts against the 160 characters of a segment: \"— Alex-Honoré, residential real-estate broker\" costs 45 characters per send.",
  },
  "identity.aiDisclosure": {
    label: "AI disclosure",
    what: "When the assistant states that it is an automated system.",
    why: "In both cases it tells the truth if asked — that is a core rule, non-negotiable. This setting only decides whether it says so without being asked.",
    effect: "In \"upfront\" mode, an L1 instruction requires it to state so in the first message.",
    pitfalls: "Disclosing upfront lowers the reply rate; not disclosing exposes you to the person's disappointment if they find out late. The \"honesty_ai\" guardrail covers the worst case under both settings.",
    allowed: {
      "on_request": "On request — tells the truth if asked",
      "upfront": "Upfront — states it in the very first message",
    },
  },
  "goal.primary.type": {
    label: "Primary goal — type",
    what: "What the assistant is trying to obtain at this rung of the goal.",
    why: "This is the structuring decision: it determines which tools are useful, which fields to collect, and what counts as success.",
    effect: "Compiled in L2 and re-read on every turn in the execution layer. Meeting types trigger a search for real availability; \"qualify_only\" forbids any offer of an appointment.",
    pitfalls: "Choosing a meeting type with no Google calendar connected: the assistant has no availability to offer and goes in circles. Symptom: conversations that drag on without ever proposing a time.",
    allowed: {
      "video_meeting": "Video meeting — video call with the broker",
      "in_person_meeting": "In-person meeting — at the office or at the client's place",
      "phone_call": "Phone call — a reserved time slot",
      "collect_email": "Get the e-mail — for a follow-up send",
      "collect_callback_time": "Agree on a callback time",
      "qualify_only": "Qualify only — NEVER offers a meeting",
      "handoff": "Hand over — aims for a takeover by a human",
    },
  },
  "goal.primary.durationMin": {
    label: "Primary goal — duration (minutes)",
    what: "The meeting length that is announced.",
    why: "A short, named duration defeats the \"I don't have time\" objection. \"15 minutes\" is harder to refuse than \"a meeting\".",
    effect: "Quoted in L2 and carried over into the calendar event.",
    pitfalls: "Announcing 15 minutes then blocking an hour of calendar: the broker ends up with holes. The duration has to match the actual booking.",
  },
  "goal.primary.appointmentType": {
    label: "Primary goal — appointment type",
    what: "The CRM appointment type this rung is attached to — it is what decides which availability is consulted.",
    why: "Video and in-person meetings have neither the same duration nor the same buffer in your booking settings. Linking it explicitly avoids offering an impossible time slot.",
    effect: "Passed to the availability search and to the creation of the appointment. With no value, the calendar tools refuse to act.",
    pitfalls: "A meeting type with no appointment type: the assistant can neither offer nor book, and the conversation bogs down.",
    allowed: {
      "meet": "Video conference (Google Meet link)",
      "inperson": "In person (address)",
      "null": "None — this rung does not book",
    },
  },
  "goal.primary.withUserId": {
    label: "Primary goal — broker",
    what: "The user the appointment is booked with.",
    why: "In a team, the appointment has to land on the right calendar. This field is re-bound to a local user at import.",
    effect: "Owner of the appointment created.",
    pitfalls: "Left empty, the appointment falls back to the client's assignee and then to the first active admin — which is not always the right person.",
  },
  "goal.primary.requiredFields": {
    label: "Primary goal — required information",
    what: "The information the assistant must have collected BEFORE it is allowed to book. The eight keys below are offered with a label; any other text is accepted as-is (\"number of bedrooms\", \"address to appraise\") and goes into the prompt word for word.",
    why: "Without that barrier, a model books as soon as the person says yes, and the broker walks into the meeting not knowing whether it is a purchase or a sale.",
    effect: "The booking tool REFUSES as long as a field is missing and returns an error the model has to read: it then asks the question instead of booking.",
    pitfalls: "Too many required fields: the conversation turns into a form and the person drops off. Two is almost always enough. Symptom: plenty of long conversations with no appointment.",
    allowed: {
      "project_type": "project_type",
      "timing": "timing",
      "budget": "budget",
      "sector": "sector",
      "financing": "financing",
      "current_situation": "current_situation",
      "email": "email",
      "preferred_time": "preferred_time",
    },
  },
  "goal.primary.slotOfferCount": {
    label: "Primary goal — number of time slots offered",
    what: "How many real time slots the assistant offers at a time.",
    why: "Two choices turn \"do you want to meet?\" into \"which of the two?\" — a far easier question to answer. Three starts to look like a schedule.",
    effect: "Number of availabilities requested from the calendar and quoted in the message.",
    pitfalls: "Three time slots in an SMS lengthen the message and dilute the question.",
    allowed: {
      "1": "1 — a single proposal",
      "2": "2 — recommended",
      "3": "3 — maximum",
    },
  },
  "goal.primary.instruction": {
    label: "Primary goal — how to ask for it",
    what: "A free instruction on HOW to present this rung: \"offer the call as a quick fifteen-minute check-in, not as a meeting\".",
    why: "The goal type says what you are trying to obtain; it says nothing about how to ask for it. Yet the manner is what gets a yes or a no — and it fitted in no setting: you had to rewrite a whole prompt layer to express it.",
    effect: "Rendered in L2 right after the rung it belongs to — not in a block at the end, where you can no longer tell which fallback it applies to.",
    pitfalls: "An instruction that contradicts a guardrail (\"promise a free valuation\") will be blocked on send without the model understanding why. It describes a TONE, not a permission.",
  },
  "goal.primary.confirmationTemplate": {
    label: "Primary goal — confirmation message",
    what: "Template for the message sent once the appointment is confirmed. Empty = built-in wording.",
    why: "The confirmation is the most re-read message of the conversation: putting the time, the format and the name in it prevents a no-show.",
    effect: "Rendered with the turn's variables at the moment of confirmation.",
    pitfalls: "A template that leaves out the time or the time zone: the person shows up at the wrong moment.",
  },
  "goal.fallbacks": {
    label: "Fallback chain",
    what: "The backup goals, in order, for when the person puts it off without refusing.",
    why: "Someone who says \"not this week\" has not said no — they have said no TO THIS request. Going down one rung (30-min video → 15-min call → e-mail) converts a share of these people; pressing the same request again loses them.",
    effect: "ONE soft refusal = ONE rung down. A FIRM refusal never touches the chain: the conversation is closed. The current rung is written into the execution layer on every turn.",
    pitfalls: "Too long a chain drags out conversations that are already lost. Two fallbacks are almost always enough. Careful: the chain NEVER rescues a real refusal — it applies only to postponements.",
  },
  "goal.fallbacks[].type": {
    label: "Fallback — type",
    what: "What the assistant is trying to obtain at this rung of the goal.",
    why: "This is the structuring decision: it determines which tools are useful, which fields to collect, and what counts as success.",
    effect: "Compiled in L2 and re-read on every turn in the execution layer. Meeting types trigger a search for real availability; \"qualify_only\" forbids any offer of an appointment.",
    pitfalls: "Choosing a meeting type with no Google calendar connected: the assistant has no availability to offer and goes in circles. Symptom: conversations that drag on without ever proposing a time.",
    allowed: {
      "video_meeting": "Video meeting — video call with the broker",
      "in_person_meeting": "In-person meeting — at the office or at the client's place",
      "phone_call": "Phone call — a reserved time slot",
      "collect_email": "Get the e-mail — for a follow-up send",
      "collect_callback_time": "Agree on a callback time",
      "qualify_only": "Qualify only — NEVER offers a meeting",
      "handoff": "Hand over — aims for a takeover by a human",
    },
  },
  "goal.fallbacks[].durationMin": {
    label: "Fallback — duration (minutes)",
    what: "The meeting length that is announced.",
    why: "A short, named duration defeats the \"I don't have time\" objection. \"15 minutes\" is harder to refuse than \"a meeting\".",
    effect: "Quoted in L2 and carried over into the calendar event.",
    pitfalls: "Announcing 15 minutes then blocking an hour of calendar: the broker ends up with holes. The duration has to match the actual booking.",
  },
  "goal.fallbacks[].appointmentType": {
    label: "Fallback — appointment type",
    what: "The CRM appointment type this rung is attached to — it is what decides which availability is consulted.",
    why: "Video and in-person meetings have neither the same duration nor the same buffer in your booking settings. Linking it explicitly avoids offering an impossible time slot.",
    effect: "Passed to the availability search and to the creation of the appointment. With no value, the calendar tools refuse to act.",
    pitfalls: "A meeting type with no appointment type: the assistant can neither offer nor book, and the conversation bogs down.",
    allowed: {
      "meet": "Video conference (Google Meet link)",
      "inperson": "In person (address)",
      "null": "None — this rung does not book",
    },
  },
  "goal.fallbacks[].withUserId": {
    label: "Fallback — broker",
    what: "The user the appointment is booked with.",
    why: "In a team, the appointment has to land on the right calendar. This field is re-bound to a local user at import.",
    effect: "Owner of the appointment created.",
    pitfalls: "Left empty, the appointment falls back to the client's assignee and then to the first active admin — which is not always the right person.",
  },
  "goal.fallbacks[].requiredFields": {
    label: "Fallback — required information",
    what: "The information the assistant must have collected BEFORE it is allowed to book. The eight keys below are offered with a label; any other text is accepted as-is (\"number of bedrooms\", \"address to appraise\") and goes into the prompt word for word.",
    why: "Without that barrier, a model books as soon as the person says yes, and the broker walks into the meeting not knowing whether it is a purchase or a sale.",
    effect: "The booking tool REFUSES as long as a field is missing and returns an error the model has to read: it then asks the question instead of booking.",
    pitfalls: "Too many required fields: the conversation turns into a form and the person drops off. Two is almost always enough. Symptom: plenty of long conversations with no appointment.",
    allowed: {
      "project_type": "project_type",
      "timing": "timing",
      "budget": "budget",
      "sector": "sector",
      "financing": "financing",
      "current_situation": "current_situation",
      "email": "email",
      "preferred_time": "preferred_time",
    },
  },
  "goal.fallbacks[].slotOfferCount": {
    label: "Fallback — number of time slots offered",
    what: "How many real time slots the assistant offers at a time.",
    why: "Two choices turn \"do you want to meet?\" into \"which of the two?\" — a far easier question to answer. Three starts to look like a schedule.",
    effect: "Number of availabilities requested from the calendar and quoted in the message.",
    pitfalls: "Three time slots in an SMS lengthen the message and dilute the question.",
    allowed: {
      "1": "1 — a single proposal",
      "2": "2 — recommended",
      "3": "3 — maximum",
    },
  },
  "goal.fallbacks[].instruction": {
    label: "Fallback — how to ask for it",
    what: "A free instruction on HOW to present this rung: \"offer the call as a quick fifteen-minute check-in, not as a meeting\".",
    why: "The goal type says what you are trying to obtain; it says nothing about how to ask for it. Yet the manner is what gets a yes or a no — and it fitted in no setting: you had to rewrite a whole prompt layer to express it.",
    effect: "Rendered in L2 right after the rung it belongs to — not in a block at the end, where you can no longer tell which fallback it applies to.",
    pitfalls: "An instruction that contradicts a guardrail (\"promise a free valuation\") will be blocked on send without the model understanding why. It describes a TONE, not a permission.",
  },
  "goal.fallbacks[].confirmationTemplate": {
    label: "Fallback — confirmation message",
    what: "Template for the message sent once the appointment is confirmed. Empty = built-in wording.",
    why: "The confirmation is the most re-read message of the conversation: putting the time, the format and the name in it prevents a no-show.",
    effect: "Rendered with the turn's variables at the moment of confirmation.",
    pitfalls: "A template that leaves out the time or the time zone: the person shows up at the wrong moment.",
  },
  "approach.formality": {
    label: "Form of address",
    what: "Formal or familiar address — the French second-person distinction.",
    why: "In Québec, opening a business contact with \"tu\" can come across as misplaced familiarity — especially for a transaction of this size.",
    effect: "A writing instruction in L3.",
    pitfalls: "Switching form of address mid-conversation is noticed immediately and rings false.",
    allowed: {
      "vous": "Formal address — recommended in Québec for a first contact",
      "tu": "Familiar address",
    },
  },
  "approach.persistence": {
    label: "Persistence",
    what: "How many times the assistant asks again for the appointment after a soft refusal, how long the follow-up ladder runs, and when the closing message goes out.",
    why: "It separates a cold-reactivation assistant, which has to let go fast, from an assistant working a warm Facebook lead, where two follow-ups are normal.",
    effect: "Compiled into L3 and read by the follow-up engine. Level 3: two re-asks, five touches, closing message on day 14.",
    pitfalls: "Beyond 3, the opt-out rate climbs before the booking rate does. An opt-out rate above 3% is almost always persistence set too high, not a bad opening message. Persistence NEVER overrides an explicit refusal.",
    allowed: {
      "1": "1 — a single ask, then lets go",
      "2": "2 — one gentle follow-up",
      "3": "3 — up to two spaced-out follow-ups",
      "4": "4 — follows up steadily",
      "5": "5 — insists",
    },
  },
  "approach.questionBudget": {
    label: "Question budget",
    what: "The TOTAL number of qualification questions the assistant may ask in the whole conversation. It has to obtain the required information within that budget; once spent, it offers with what it has.",
    why: "Every question is one more chance for the person not to answer. Qualifying enough without turning the exchange into an interrogation is the central trade-off of an SMS assistant.",
    effect: "A numeric instruction in L3. It is an ABSOLUTE ceiling since 2026-08-22: the previous wording (\"before the first offer\") let the assistant restart an interrogation after a first refusal, as if the counter reset.",
    pitfalls: "Beyond 3, the mid-conversation drop-off rate rises noticeably. Symptom: threads that stop after the second or third question.",
  },
  "approach.maxChars": {
    label: "Maximum length",
    what: "The maximum length of an outgoing message, in characters.",
    why: "A long SMS reads like a mass mailing. It also costs more: past 160 characters (or 70 with an accent outside the GSM table), the message is billed as several segments.",
    effect: "An instruction in L3, and a guardrail rule can enforce it at send time.",
    pitfalls: "A high maximum produces two- or three-segment messages: multiplied cost and painful reading on a phone.",
  },
  "approach.proactivity": {
    label: "Proactivity",
    what: "How far the assistant proposes instead of waiting.",
    why: "Low proactivity answers the questions asked; high proactivity steers systematically back to booking the appointment.",
    effect: "Tone and framing in L3.",
    pitfalls: "Set too high, every reply ends with the same ask and the thread turns repetitive.",
  },
  "approach.warmth": {
    label: "Warmth",
    what: "Emotional register: curt and efficient, or warm.",
    why: "The same message can reassure or come across as brusque depending on the tone. An anxious seller responds better to warmth; a buyer in a hurry, to efficiency.",
    effect: "Tone in L3.",
    pitfalls: "Maximum warmth produces canned phrases (\"Great news!\") that sound artificial over SMS.",
  },
  "approach.emoji": {
    label: "Emoji",
    what: "Whether emoji are allowed.",
    why: "Beyond tone, one emoji flips the whole message into UCS-2 encoding: capacity drops from 160 to 70 characters and the sending cost goes up.",
    effect: "An instruction in L3; the segment analyser measures the real effect.",
    pitfalls: "A single emoji can double the segment count of an already long message — a cost that stays invisible until the bill. \"A lot\" therefore doubles the cost of nearly every send, and a very casual tone on first contact gets the message reported as spam.",
    allowed: {
      "none": "None — maximum capacity, minimum cost",
      "rare": "Rare — at most one, occasionally",
      "moderate": "Moderate — one per message when the tone calls for it",
      "lots": "A lot — two or three per message, decidedly casual",
    },
  },
  "approach.replySpeed": {
    label: "Reply speed",
    what: "The delay before the reply is sent.",
    why: "A reply in 400 milliseconds signals a machine more surely than any turn of phrase. A slight delay reads as someone busy but attentive.",
    effect: "Shifts when the send is queued; quiet hours then apply on top.",
    pitfalls: "\"Deliberate\" in the middle of a live conversation feels like being ignored; it is mostly useful for a first contact.",
    allowed: {
      "instant": "Instant",
      "natural": "Natural — about 30 seconds",
      "deliberate": "Deliberate — about 90 seconds",
    },
  },
  "approach.maxTurns": {
    label: "Message budget",
    what: "The total number of messages the assistant may send in a conversation before handing over.",
    why: "A conversation that has not landed within fifteen or so messages will not land on its own. This limit guarantees a human eventually sees the thread.",
    effect: "Only the ASSISTANT's messages count — a caller's manual reply does not eat into the budget. At the ceiling, the conversation is flagged \"To handle\" and the AI goes silent.",
    pitfalls: "Too low, and promising conversations are cut off in the middle. Too high, and nobody ever looks at the threads going in circles.",
  },
  "knowledge.claims": {
    label: "Knowledge and instructions",
    what: "The ORDERED list of what the assistant knows and what it must do. An entry is either a business fact it is allowed to assert, or an instruction on how to behave — \"if the person asks about the price, answer that Alex is the one who discusses it\", \"never talk about the commission\", \"start by thanking them for their request\".",
    why: "The core forbids inventing anything: for facts, this list is the only way out — what is not in it cannot be asserted. For behaviour, this is where you dictate the sequence without rewriting the prompt: \"in this order, if… then…\".",
    effect: "Compiled into L4, in the order entered and numbered. The prompt states explicitly that a fact entry is to be asserted and an instruction entry is to be applied, and that in case of contradiction the FIRST one wins. An empty list forbids any business claim at all.",
    pitfalls: "Everything written here will be asserted IN WRITING, in the name of a licensed broker: a statistic, a promise about timing or a market figure becomes a statement the broker answers for before the OACIQ. And an instruction here NEVER lifts a guardrail — \"give the price\" written here will be blocked at send time, with the model none the wiser as to why.",
  },
  "objectionPacks": {
    label: "Objection packs",
    what: "The packs of answers to common objections the assistant can draw on.",
    why: "Without them, the model improvises when it hits \"I already have a broker\" — and sometimes improvises something inaccurate or too pushy. A pack fixes the structure: acknowledge, reframe, ask again.",
    effect: "Rendered in L5, pack by pack, in the order chosen.",
    pitfalls: "Loading every pack lengthens the prompt for nothing: a seller assistant has no need of buyer objections.",
  },
  "tools": {
    label: "Enabled tools",
    what: "The tools the assistant is allowed to call.",
    why: "A missing tool is a missing capability: the model cannot work around the list. This is a capability guardrail, not just a convenience.",
    effect: "Only the checked tools are presented to the model on each turn.",
    pitfalls: "Offering seven tools to a model that cannot handle them fails silently and looks like a prompt bug — the model picker shows tool support for exactly this reason.",
  },
  "tools.get_slots": {
    label: "\"get_slots\" tool",
    what: "Returns the broker's REAL availability.",
    why: "Without this tool, the model offers made-up times and the client runs into a refusal at the moment of confirming.",
    pitfalls: "Turning it off on a meeting goal leaves the assistant unable to propose a time.",
  },
  "tools.book_meeting": {
    label: "\"book_meeting\" tool",
    what: "Creates the appointment in the calendar.",
    why: "This is the payoff: without it, the assistant can only promise a callback.",
    pitfalls: "Turning it off forces the goal down to \"qualify only\". The tool REFUSES as long as a required field is missing.",
  },
  "tools.update_qualification": {
    label: "\"update_qualification\" tool",
    what: "Records what the person has just revealed.",
    why: "What is not recorded is lost again on the next turn — and the client gets asked the same question over.",
    pitfalls: "Turning it off makes the assistant go in circles over the same questions.",
  },
  "tools.schedule_followup": {
    label: "\"schedule_followup\" tool",
    what: "Schedules a follow-up on an agreed date.",
    why: "\"Call me back in June\" is only worth something if something remembers in June.",
    pitfalls: "Without it, far-off postponements are lost.",
  },
  "tools.set_category": {
    label: "Tool \"set_category\"",
    what: "Files the record into a pipeline category, according to the classification rules.",
    why: "The assistant learns in two messages what takes a caller a whole call to find out — \"I want to buy, but next year\", \"I'm in Saguenay\". Without this tool the information stays in the thread and the record sleeps in \"Not contacted\" until someone re-reads it.",
    pitfalls: "With no classification rule configured the tool has NO permitted category and is never called — it does nothing until the rules are written. A rule pointing at \"Do not call\" would let the assistant remove someone from the pipeline on a misread sentence: set that category by hand.",
  },
  "tools.stop": {
    label: "\"stop\" tool",
    what: "Stops for good and deletes the number.",
    why: "This is the tool for honouring a refusal. Turning it off does not prevent opt-outs — the STOP keyword is handled upstream, outside the model — but it deprives the assistant of any way to stop cleanly on a natural-language phrasing.",
    pitfalls: "Never to be turned off.",
  },
  "tools.handoff": {
    label: "\"handoff\" tool",
    what: "Hands the conversation over to a human.",
    why: "An assistant that cannot hand over keeps pushing in the face of a legal question, a complaint or hostility.",
    pitfalls: "Never to be turned off.",
  },
  "tools.transfer_assistant": {
    label: "\"transfer_assistant\" tool",
    what: "Switches the conversation over to another assistant.",
    why: "A buyer lead that turns out to be a seller deserves the seller assistant, not a badly framed conversation.",
    pitfalls: "A transfer loop is possible if two assistants keep passing the ball back and forth.",
  },
  "tools.close_conversation": {
    label: "\"close_conversation\" tool",
    what: "Closes the conversation with an outcome.",
    why: "It separates a thread that reached an outcome from an abandoned one in the statistics.",
    pitfalls: "Closing too early skews the conversion rate.",
  },
  "model.provider": {
    label: "Provider",
    what: "Where the calls to the model go through.",
    why: "OpenRouter gives you a single integration and model switching without a redeploy; it costs a network hop, a margin, and ONE more intermediary to list in a Law 25 assessment. A direct provider removes that intermediary, at the price of a second key.",
    effect: "Chooses which implementation is used; the routing object only applies to OpenRouter.",
    pitfalls: "Changing provider also changes the model ids: \"anthropic/claude-sonnet-5\" on OpenRouter is called \"claude-sonnet-5\" direct.",
    allowed: {
      "openrouter": "OpenRouter — one access point, every model",
      "anthropic": "Anthropic — direct",
      "google": "Google — direct",
      "openai": "OpenAI — direct",
    },
  },
  "model.model": {
    label: "Generator model",
    what: "The model that writes the messages.",
    why: "It is the one that holds — or fails to hold — the constraints: a single question, no prices, no invention. The gaps between models show up mostly there.",
    effect: "Used on every turn; the model actually served is recorded in the trace.",
    pitfalls: "A non-existent id makes ALL calls fail: the judges then fail closed and no message goes out at all. Check the id in the picker instead of typing it. Avoid \"-latest\" aliases, which disappear without notice.",
  },
  "model.temperature": {
    label: "Temperature",
    what: "How much the answers vary, from 0 to 1.",
    why: "Too low and the messages become identical from one lead to the next — and carriers detect repeated content. Too high and the model drifts away from its instructions.",
    effect: "Passed to the provider as is.",
    pitfalls: "Above 0.8, deviations from the guardrails increase and the block rate goes up.",
  },
  "model.maxTokens": {
    label: "Maximum tokens",
    what: "The maximum length of the model's reply, in tokens.",
    why: "An SMS is short; leaving headroom costs and brings nothing.",
    effect: "The cap sent to the provider.",
    pitfalls: "Too low and the reply is cut off mid-sentence and goes out truncated. 300 leaves the headroom that is needed.",
  },
  "model.reasoningEffort": {
    label: "Reasoning effort",
    what: "How much the model thinks before answering, when it is able to.",
    why: "More thinking improves the hard decisions — which tool to call, whether to hand over. On a two-sentence SMS, it changes almost nothing in the wording.",
    effect: "Sent to the provider (router or direct) in its own dialect, on every call, only when it differs from \"none\".",
    pitfalls: "Thinking is BILLED in tokens and adds latency: a high level can add several seconds before every reply, which is noticeable in a conversation. Sending it to a model that does not support it gets the whole request rejected — the picker only offers the setting for compatible models.",
    allowed: {
      "none": "None — the model answers directly",
      "low": "Light",
      "medium": "Medium",
      "high": "High — thinks at length before writing",
    },
  },
  "model.classifier.provider": {
    label: "Classifier provider",
    what: "Where the classifier's and the judges' calls go through.",
    why: "The classifier runs on every inbound message and the judges on every draft: it is the most cost-sensitive item in the engine.",
    effect: "Used for classification and for \"llm_judge\" rules.",
    pitfalls: "An unconfigured provider makes the judges fail — and therefore blocks everything.",
    allowed: {
      "openrouter": "OpenRouter",
      "anthropic": "Anthropic — direct",
      "google": "Google — direct",
      "openai": "OpenAI — direct",
    },
  },
  "model.classifier.model": {
    label: "Classifier model",
    what: "The model that classifies inbound messages (opt-out, refusal, qualification) and that judges the drafts.",
    why: "These tasks are mechanical: a cheap, fast model is enough for them. Mixing a cheap classifier with a strong generator is the INTENDED configuration, not an edge case.",
    effect: "Called once per inbound message, and once more for each \"llm_judge\" rule.",
    pitfalls: "An invalid id makes the judges fail, and they fail closed: NO message goes out any more and the conversation is flagged \"guardrail unavailable\". That is exactly what happens with a \"-latest\" alias that has been withdrawn.",
  },
  "model.fallback": {
    label: "Fallback",
    what: "The provider and the model used if the main one fails in a retryable way.",
    why: "A 5xx outage or a timeout must not silence the assistant. The fallback is explicit here, never decided by the router.",
    effect: "A retryable error triggers ONE single retry on the fallback. A non-retryable error (a malformed request) is surfaced as is.",
    pitfalls: "Forgetting that the model id differs on the fallback: the retry then fails too.",
  },
  "model.routing.dataCollection": {
    label: "Data collection (OpenRouter)",
    what: "Forbids downstream providers from training their models on these exchanges.",
    why: "These prompts contain names, phone numbers, budgets and the moving plans of Québec residents. This is not test data.",
    effect: "Sent in the routing object on every call.",
    pitfalls: "This setting is NOT the same as ZDR: one forbids training, the other retention. You need both.",
    allowed: {
      "deny": "Deny — recommended",
      "allow": "Allow",
    },
  },
  "model.routing.zdr": {
    label: "Zero retention (ZDR)",
    what: "Routes only to providers that do not keep prompts at rest.",
    why: "The indispensable complement to the previous setting: a provider can honour one without the other.",
    effect: "Sent in the routing object; it narrows the pool of available providers.",
    pitfalls: "Narrowing the pool can increase latency or reduce availability. That is expected — do not \"fix\" it by turning the option off.",
  },
  "model.routing.allowFallbacks": {
    label: "Automatic rerouting (OpenRouter)",
    what: "Whether the router may switch to another downstream provider on its own.",
    why: "A silent reroute to a provider whose data path has not been vetted cancels exactly the guarantee you have just put in place. A visible outage is better.",
    effect: "Sent in the routing object. Our own fallback stays explicit.",
    pitfalls: "Turning it on to \"improve availability\" reintroduces the uncertainty about how the data is handled.",
  },
  "model.routing.only": {
    label: "Allowed providers",
    what: "Restricts routing to a list of downstream providers.",
    why: "Useful when a compliance assessment has only cleared certain hosts.",
    effect: "Sent in the routing object when the list is not empty.",
    pitfalls: "Too narrow a list causes intermittent outages.",
  },
  "promptMode": {
    label: "Prompt mode",
    what: "How the system prompt is produced.",
    why: "Composed mode keeps the config and the prompt in sync. Raw mode gives you full control when a case falls outside the frame — at the price of having to maintain everything by hand.",
    effect: "In raw mode the compiler is bypassed: the config keeps driving the runtime (steps, required fields, tools, guardrails) but no longer writes a single line of the prompt.",
    pitfalls: "Switching to raw freezes the text: a change in a tab no longer flows through to it, and neither does a new version of the core. Going back to composed mode keeps the raw text without using it.",
    allowed: {
      "composed": "Composed — assembled from the tabs",
      "raw": "Raw — a single document that you write",
    },
  },
  "systemPromptOverride": {
    label: "Raw prompt",
    what: "The complete system prompt, used when the mode is \"raw\".",
    why: "Lets you take full control back, without losing the structured configuration.",
    effect: "Replaces L0 through L6. If the text contains {{runtime}}, the runtime layer is inserted there; otherwise it is appended at the end.",
    pitfalls: "Copying the core into it without its OACIQ limits removes the professional protections from the prompt — the runtime guardrails still hold, but the model is no longer guided.",
  },
  "layerOverrides": {
    label: "Per-layer overrides",
    what: "Replaces or extends one specific layer of the compiled prompt, without giving up the others.",
    why: "Often only one layer needs adjusting. Switching the whole prompt to raw just for that would lose the synchronization of everything else.",
    effect: "\"replace\" substitutes the generated block; \"append\" writes yours after it. The modified layer is flagged in the Prompt tab, with a diff against its generated version.",
    pitfalls: "Replacing L0 removes the professional core from this prompt: the OACIQ limits are no longer stated to the model.",
  },
  "turnInstructions": {
    label: "Runtime layer template (L7)",
    what: "The block rebuilt on EVERY turn: lead context, qualification, current step, availability, local time.",
    why: "This is what gives the model the real state of the conversation. Without it, it improvises from the history alone.",
    effect: "Rendered with the turn's variables and appended to the compiled prompt.",
    pitfalls: "An unknown variable renders as an empty string and raises a warning — never an error: a typo must not interrupt a conversation. Removing {{slots}} makes it propose made-up times.",
  },
  "includeRuntimeLayer": {
    label: "Include the runtime layer",
    what: "Whether the L7 block is added to the prompt on every turn.",
    why: "Turning it off only makes sense if the raw prompt rebuilds that state some other way.",
    effect: "At false, the model receives neither the current step nor the real availability.",
    pitfalls: "Disabled, the assistant does not know the current goal or the available times: it proposes moments that do not exist. The runtime still requires the required fields before booking, but the model no longer knows which ones they are.",
  },
  "requireSuitePass": {
    label: "Require a green suite",
    what: "Prevents activation as long as the guardrail suite is not green.",
    why: "It is the barrier between \"it compiles\" and \"it behaves correctly\". Turning it off remains possible — the suite still runs and is still displayed — but a failure becomes a warning instead of a block.",
    effect: "Checked in the server action AND by a database trigger: a direct write does not bypass the gate. The recompile requirement, for its part, always holds.",
    pitfalls: "Disabled, an assistant can go to production with a red blocking fixture — for example one that does not honour a STOP.",
  },
  "name": {
    label: "Assistant name",
    what: "The assistant's internal name, visible only to your team.",
    why: "It is what tells it apart in lists, campaigns and traces.",
    pitfalls: "Two assistants with near-identical names make the statistics hard to read.",
  },
  "description": {
    label: "Description",
    what: "What this assistant is for, for your team.",
    why: "Six months later, \"Buyer FB 2\" no longer means anything to anyone.",
  },
  "secondaryLanguage": {
    label: "Second language",
    what: "A language the assistant is allowed to SWITCH to when the person writes in it — never to open with.",
    why: "A Québec City broker gets English-speaking leads. Without this field the assistant answered in French to someone who had just written in English, and the conversation ended there.",
    effect: "Adds two lines in L3: answer in that language if the person moves to it, but keep the primary language for the FIRST message — you do not guess the language of someone who has not written yet.",
    pitfalls: "The same value as the primary language is refused on save: the setting would have no effect while looking as if it had one.",
    allowed: {
      "null": "None — a single language",
      "fr-CA": "Québec French",
      "en-CA": "Canadian English",
    },
  },
  "language": {
    label: "Primary language",
    what: "The language the assistant writes ALL its messages in, starting with the first one.",
    why: "A regional tag rather than plain \"fr\": what we ask the model for is Québec French, not the French of France. The difference is audible in the first sentence of a text message.",
    effect: "Compiled into L3, spelled out. Without that line the model wrote in French because the rest of the prompt was — not because it had been asked to, and an assistant set to English still wrote in French.",
    pitfalls: "Objection packs and the turn template are written in French: on an English assistant the model translates them on the fly. Check the sandbox before activating.",
    allowed: {
      "fr-CA": "Québec French",
      "en-CA": "Canadian English",
    },
  },
  "model.fallback.provider": {
    label: "Fallback provider",
    what: "The provider used when the main one fails in a retryable way.",
    why: "A fallback at ANOTHER provider protects you from an outage at the first; a fallback at the same one only protects you from a passing incident.",
    effect: "Used for the single retry after a retryable error.",
    pitfalls: "Choosing a provider whose key is not configured: the fallback fails too and the turn ends in an escalation.",
    allowed: {
      "openrouter": "OpenRouter",
      "anthropic": "Anthropic — direct",
      "google": "Google — direct",
      "openai": "OpenAI — direct",
    },
  },
  "model.fallback.model": {
    label: "Fallback model",
    what: "The model called at the fallback provider.",
    why: "Ids differ from one provider to the next: the fallback needs its own.",
    effect: "Replaces the model id during the fallback attempt.",
    pitfalls: "Copying the router's id into it (\"anthropic/claude-sonnet-5\") when the direct provider expects \"claude-sonnet-5\": the fallback fails at exactly the moment you need it.",
  },
  "layerOverrides.mode": {
    label: "Override mode",
    what: "How your text fits together with the generated layer.",
    why: "\"Append\" covers most needs: one more detail without losing what the configuration produces. \"Replace\" is the strong move.",
    effect: "Applied layer by layer at compilation; the layer is marked as modified.",
    pitfalls: "Replacing a layer freezes its content: the tabs that fed it no longer have any effect, with no signal other than the \"modified\" badge.",
    allowed: {
      "replace": "Replace — the generated block disappears",
      "append": "Append — your text follows the generated block",
    },
  },
  "layerOverrides.text": {
    label: "Override text",
    what: "The text that replaces or extends the layer.",
    why: "It is the escape hatch when the structured configuration does not say exactly what is needed.",
    effect: "Inserted as is into the compiled prompt, in place of or after the generated block.",
    pitfalls: "Text that contradicts another layer (for example allowing what the guardrails forbid) produces a hesitant model and blocks at send time.",
  },
};
